export const NOT_STARTED = 'NOT_STARTED'
export const WAITING_FOR_GUESS = 'WAITING_FOR_GUESS'
export const CORRECT_GUESS = 'CORRECT_GUESS'
export const INCORRECT_GUESS = 'INCORRECT_GUESS'
export const GAME_OVER = 'GAME_OVER'

export const HAS_GUESSED_STATUSES = [
  CORRECT_GUESS,
  INCORRECT_GUESS
]

export const GAME_IN_PROGRESS_STATUSES = [
  WAITING_FOR_GUESS,
  CORRECT_GUESS,
  INCORRECT_GUESS
]

export const STATUSES = {
  NOT_STARTED,
  WAITING_FOR_GUESS,
  CORRECT_GUESS,
  INCORRECT_GUESS,
  GAME_OVER
}
