import { CORRECT_GUESS, INCORRECT_GUESS, GAME_OVER } from './types'
export const NOT_STARTED = 'NOT_STARTED'
export const WAITING_FOR_GUESS = 'WAITING_FOR_GUESS'

export const HAS_GUESSED_STATUSES = [CORRECT_GUESS, INCORRECT_GUESS]

export const GAME_IN_PROGRESS_STATUSES = [
  WAITING_FOR_GUESS,
  CORRECT_GUESS,
  INCORRECT_GUESS
]

export const STATUSES = {
  NOT_STARTED,
  WAITING_FOR_GUESS,
  CORRECT_GUESS,
  INCORRECT_GUESS,
  GAME_OVER
}
