export const SET_ACTIVE_LOGO = 'SET_ACTIVE_LOGO'
export const SET_LOGOS = 'SET_LOGOS'
export const START_GAME = 'START_GAME'
export const CORRECT_GUESS = 'CORRECT_GUESS'
export const INCORRECT_GUESS = 'INCORRECT_GUESS'
export const RESET_GAME = 'RESET_GAME'
export const GAME_OVER = 'GAME_OVER'
